# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 33242
spring:
  user:
    timeLength: 300000
    count: 5
    operationTimeBetween: 60000000000
    ttlMillis: 999999999
    JWT_SECRET: 7786df7fc3a34e26a61c034d5ec8245d
  jpa:
    database: MYSQL
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://localhost:3306/faction?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: root
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvactionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    host: 192.168.99.229
    port: 6379
    database: 0
    password: gb.2312
    jedis:
      pool:
        max-active: 600
        max-wait: -1ms
        max-idle: 300
        min-idle: 20
    timeout: 6000ms
    saveTime: 1
#  resources:
#    static-locations: classpath:/static/,classpath:/views/ #,file:${web.upload},file:${web.ueditorUpload}
#  datasource:
#    driver-class-name: org.sqlite.JDBC
#    # 方式一：  引用外部文件
#    url: jdbc:sqlite:E:\idea\product\HongTu\resource\static\sqlite\faction.db
#    #方式二： 引用项目中的文件
##    url: jdbc:sqlite::resource:static/sqlite/faction.db
#    username:
#    password:

mybatis:
  mapper-locations: classpath:mappers/*.xml
# sql打印
logging:
  level: debug
  level.com.xuanyin: debug
  path: logs/
#    file: admin.log
