# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 33242
#spring
spring:
  redis:
    host: 192.168.99.115
    port: 6379
    database: 0
    password: 123456
    jedis:
      pool:
        max-active: 600
        max-wait: -1ms
        max-idle: 300
        min-idle: 20
    timeout: 6000ms
    saveTime: 1
  resources:
    static-locations: classpath:/static/,classpath:/views/ #,file:${web.upload},file:${web.ueditorUpload}
  datasource:
    driver-class-name: org.sqlite.JDBC
    # 方式一：  引用外部文件
    url: jdbc:sqlite:E:\idea\product\HongTu\resource\static\sqlite\fiction.db
    #方式二： 引用项目中的文件
#    url: jdbc:sqlite::resource:static/sqlite/fiction.db
    username:
    password:

mybatis:
  mapper-locations: classpath:mappers/*.xml
# sql打印
logging:
  level: debug
  level.com.xuanyin: debug
  path: logs/
#    file: admin.log
