# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 33242
spring:
  user:
    timeLength: 300000
    count: 5
    operationTimeBetween: 60000000000
    ttlMillis: 999999999
    JWT_SECRET: 7786df7fc3a34e26a61c034d5ec8245d
  jpa:
    database: MYSQL
  datasource:
    url: jdbc:mysql://192.168.99.115:3306/?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.99.229
    port: 6379
    database: 0
    password: gb.2312
    jedis:
      pool:
        max-active: 600
        max-wait: -1ms
        max-idle: 300
        min-idle: 20
    timeout: 6000ms
    saveTime: 1
#  resources:
#    static-locations: classpath:/static/,classpath:/views/ #,file:${web.upload},file:${web.ueditorUpload}
#  datasource:
#    driver-class-name: org.sqlite.JDBC
#    # 方式一：  引用外部文件
#    url: jdbc:sqlite:E:\idea\product\HongTu\resource\static\sqlite\fiction.db
#    #方式二： 引用项目中的文件
##    url: jdbc:sqlite::resource:static/sqlite/fiction.db
#    username:
#    password:

mybatis:
  mapper-locations: classpath:mappers/*.xml
# sql打印
logging:
  level: debug
  level.com.xuanyin: debug
  path: logs/
#    file: admin.log
